### PR TITLE
User can create new wallets only using passphrase

### PR DESCRIPTION
**Pull request by tynes**
User can navigate to creating a standard wallet and create one.
User must use a passphrase to encrypt the wallet.
Exact copy still needs to be defined + final styling

- [x] Basic layout
- [x] Rebase onto `BoxGrid`
- [x] User can create a new wallet
- [x] input type "password"
- [x] two passphrase inputs to validate user input

For the advanced passphrase validation:
- special character/numbers
- lowercase character
- uppercase character
- character count

### CODE REVIEW

**Comment by tynes** [comment]
screen shot 2018-10-22 at 12 36 41 pm

**Comment by tynes** [comment]
screen shot 2018-10-23 at 3 46 40 pm

MVP Functionality of creating standard wallet

**Comment by tynes** [comment]
@bucko13 ready for review

**Comment by bucko13** [comment]
@tynes can the password field support `type="password"` to obscure the input? 
screen shot 2018-10-24 at 11 42 16 am

**Comment by bucko13** [comment]
I feel like we should have user confirmation for passwords too since this can be very difficult to walk back if you get it wrong (cc: @DarrenRM)

**Comment by tynes** [comment]
Going to add 2 passphrase fields such that the passwords must match for the request to go though.

Thinking of adding a list that displays checkboxes when each criteria is fulfilled
password has:
- special character
- lowercase character
- uppercase character

any more?

**Comment by bucko13** [comment]
> any more?

**Comment by tynes** [comment]
This has been updated and is ready to be reviewed. Added a comment regarding the adding the passphrase strength checking

**Pull request merged**
